create table member_plan (
    plan_id bigint not null,
    member_id bigint not null,
    primary key (member_id, plan_id)
);

create table plan (
    id bigint generated by default as identity,
    name varchar(255),
    organization varchar(255),
    primary key (id)
);

alter table member_plan
   add constraint FKmiye2fghnr0ydqwm7ngovwb7m
   foreign key (member_id)
   references member;

alter table member_plan
   add constraint FKm05csejhnd45hd9mtiso2ivv3
   foreign key (plan_id)
   references plan;