create table organization (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

alter table plan
    add organization_id bigint;

alter table plan
   add constraint FKl5tdfk0t47faocw0b6011glqn
   foreign key (organization_id)
   references organization;

insert into organization (name)
     select distinct organization from plan;

update plan P 
   set P.organization_id = (select O.id from organization O where O.name = P.organization);

alter table plan
    drop column organization;
