= Members

== List members

List all members present in the application database.

`GET /members`

=== Parameters

|===
|Name |Type |Description

|page
|number
|The page number to return

|size
|number
|The number of members to return

|sort
|string
|What to sort members by. Can be either `firstName`, `lastName`, `dateOfBirth` or `retirement`. Default: `firstName`
|===


=== Response

`Status: 200 OK`

[source, json]
----
{
  "_embedded":{
    "members":[
      {
        "firstName":"Lisa",
        "lastName":"Simpson",
        "dateOfBirth":"1958-01-01",
        "retirement":"2018-01-01",
        "_links":{
          "self":{
            "href":"http://localhost:8080/members/1"
          },
          "member":{
            "href":"http://localhost:8080/members/1"
          },
          "plans":{
            "href":"http://localhost:8080/members/1/plans"
          }
        }
      },
      {
        "firstName":"Test",
        "lastName":"Member",
        "dateOfBirth":"1948-01-01",
        "retirement":"1985-01-12",
        "_links":{
          "self":{
            "href":"http://localhost:8080/members/2"
          },
          "member":{
            "href":"http://localhost:8080/members/2"
          },
          "plans":{
            "href":"http://localhost:8080/members/2/plans"
          }
        }
      }
    ]
  },
  "_links":{
    "self":{
      "href":"http://localhost:8080/members{?page,size,sort}",
      "templated":true
    },
    "profile":{
      "href":"http://localhost:8080/profile/members"
    }
  },
  "page":{
    "size":20,
    "totalElements":2,
    "totalPages":1,
    "number":0
  }
}
----

== Get a single member

Return a member with a given ID.

NOTE: The API returns a `404 Not Found` if a member with given ID does not exist in the database.

`GET /members/{id}`

=== Response

`Status: 200 OK`

[source, json]
----
{
  "firstName":"Lisa",
  "lastName":"Simpson",
  "dateOfBirth":"1958-01-01",
  "retirement":"2018-01-01",
  "_links":{
    "self":{
      "href":"http://localhost:8080/members/1"
    },
    "member":{
      "href":"http://localhost:8080/members/1"
    },
    "plans":{
      "href":"http://localhost:8080/members/1/plans"
    }
  }
}
----

== Create a member

A client can create a new member.

`POST /members`

=== Parameters

|===
|Name |Type |Description

|firstName
|string
|*Required.* The first name of the new member. _NOTE: cannot be blank, and cannot be longer than 255 characters_

|lastName
|string
|*Required.* The last name of the new member. _NOTE: cannot be blank, and cannot be longer than 255 characters_
|===

=== Example
[source, json]
----
{
  "firstName":"Test",
  "lastName":"Member",
  "dateOfBirth":"1958-01-01",
  "retirement":"2018-01-01"
}
----

=== Response
`Status: 201 Created` +
`Location: http://localhost:8080/members/2`
[source, json]
----
{
  "firstName":"Test",
  "lastName":"Member",
  "dateOfBirth":"1958-01-01",
  "retirement":"2018-01-01",
  "_links":{
    "self":{
      "href":"http://localhost:8080/members/2"
    },
    "member":{
      "href":"http://localhost:8080/members/2"
    },
    "plans":{
      "href":"http://localhost:8080/members/2/plans"
    }
  }
}
----

== Edit a member

A client can edit an existing member identified by the ID.

NOTE: The API returns a `404 Not Found` if a member with given ID does not exist in the database.

`PATCH /members/{id}`

=== Parameters

|===
|Name |Type |Description

|firstName
|string
|The first name of the new member. _NOTE: cannot be blank, and cannot be longer than 255 characters_

|lastName
|string
|The last name of the new member. _NOTE: cannot be blank, and cannot be longer than 255 characters_
|===

=== Example
[source, json]
----
{
  "firstName":"New",
  "lastName":"Value"
  "dateOfBirth":"1970-01-01",
  "retirement":"2038-01-19"
}
----

=== Response
`Status: 200 OK` +
`Location: http://localhost:8080/members/2`
[source, json]
----
{
  "firstName":"New",
  "lastName":"Value",
  "dateOfBirth":"1970-01-01",
  "retirement":"2038-01-19",
  "_links":{
    "self":{
      "href":"http://localhost:8080/members/2"
    },
    "member":{
      "href":"http://localhost:8080/members/2"
    },
    "plans":{
      "href":"http://localhost:8080/members/2/plans"
    }
  }
}
----

== Delete a member

A client can delete an existing member identified by the ID.

NOTE: The API returns a `404 Not Found` if a member with given ID does not exist in the database.

`DELETE /members/{id}`

=== Response
`Status: 204 No Content`

== Get the plans of a member

Return the plans of a member with a given ID.

NOTE: The API returns a `404 Not Found` if a member with given ID does not exist in the database.

`GET /members/{id}/plans`

=== Response

`Status: 200 OK`

[source, json]
----
{
  "_embedded":{
    "plans":[
      {
        "name":"Gold",
        "_links":{
          "self":{
            "href":"http://localhost:8080/plans/1"
          },
          "plan":{
            "href":"http://localhost:8080/plans/1"
          },
          "organization":{
            "href":"http://localhost:8080/plans/1/organization"
          },
          "members":{
            "href":"http://localhost:8080/plans/1/members"
          }
        }
      },
      {
        "name":"Silver",
        "_links":{
          "self":{
            "href":"http://localhost:8080/plans/2"
          },
          "plan":{
            "href":"http://localhost:8080/plans/2"
          },
          "organization":{
            "href":"http://localhost:8080/plans/2/organization"
          },
          "members":{
            "href":"http://localhost:8080/plans/2/members"
          }
        }
      }
    ]
  },
  "_links":{
    "self":{
      "href":"http://localhost:8080/members/1/plans"
    }
  }
}
----

== Add plans to a member

A client can add plans to an existing member identified by the member self link.  Plans are identified by the plan self link.

NOTE: The API returns a `200 Ok` even if a plan with given ID does not exist in the database. The plans self link can be relative. Multiple plans are separated by a newline.

`content-type: text/uri-list` +
`PATCH /members/{id}/plans`

=== Example

----
plans/1
plans/2
----

== Replace the plans of a member

A client can replace plans of an existing member identified by the member self link.  Plans are identified by the plans self link.

NOTE: The API returns a `200 Ok` even if a plan with given ID does not exist in the database. The plans self link can be relative. Multiple plans are separated by a newline. It is possible to replace the plans with zero plans.

`content-type: text/uri-list` +
`PUT /members/{id}/plans`

=== Example

----
plans/1
plans/2
----

<<<
